pipeline:
  backend:
    group: build
    image: g3rv4/transifex-builder
    when:
      branch: master
    commands:
      - "rm -rf /var/traducir-image/app/backend"
      - "mkdir -p /var/traducir-image/app/backend"

      - "cd Traducir.Api"
      - "dotnet publish -c Release -f netcoreapp2.0 -o /var/traducir-image/app/backend"
    volumes:
      - /home/gervasio/docker/traducir-image:/var/traducir-image
  frontend:
    group: build
    image: g3rv4/transifex-builder
    when:
      branch: master
    commands:
      - "rm -rf /var/traducir-image/app/frontend"
      - "mkdir -p /var/traducir-image/app/frontend"
      
      - "cd Traducir.Web"
      - "cp -r /var/node_modules node_modules"
      - "npm run build"
      - "cp -r ./dist/* /var/traducir-image/app/frontend/"
    volumes:
      - /home/gervasio/docker/traducir-image:/var/traducir-image

